name: Update Package Versions

on:
  schedule:
    # Run daily at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4

      - name: Fetch latest package versions
        run: |
          python3 update_packages.py

      - name: Apply package updates to Bazel files
        id: apply_updates
        run: |
          python3 apply_package_updates.py
          if [ $? -eq 0 ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No package updates available"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Package updates found:"
            git diff --stat
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update package versions'
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: update-packages-${{ github.run_number }}
          delete-branch: true
          title: 'chore: update package versions'
          body: |
            ## Automated Package Update

            This PR updates package versions and SHA256 hashes for:
            - Fedora 42 (x86_64, aarch64)
            - AutoSD 10 (x86_64, aarch64)
            - AutoSD 9 (x86_64, aarch64)

            ---

            🤖 This PR was automatically generated by the `update-packages` workflow.
          labels: |
            automated
            dependencies
            maintenance

      - name: Summary
        run: |
          if [ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]; then
            echo "✓ Package update PR created successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## Updated Packages" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            git diff --stat >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "  No package updates available - all packages are up to date" >> $GITHUB_STEP_SUMMARY
          fi
